# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0039_auto_20170412_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quality', models.SmallIntegerField(choices=[(1, 'Awesome'), (2, 'Good'), (3, 'Normal'), (4, 'Bad')], default=1)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
