# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0042_auto_20170417_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=100, verbose_name='reqID')),
                ('sin_data', models.CharField(max_length=300, verbose_name='\u7b7e\u540d\u6570\u636e')),
            ],
        ),
    ]
