# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0042_auto_20170417_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relancement',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
    ]
