# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0043_usb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usb',
            options={'verbose_name': 'u\u76fe\u7b7e\u540d\u6570\u636e', 'verbose_name_plural': 'u\u76fe\u7b7e\u540d\u6570\u636e'},
        ),
        migrations.AlterField(
            model_name='usb',
            name='req_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='reqID'),
        ),
    ]
