# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0043_auto_20170424_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certufucate',
        ),
        migrations.DeleteModel(
            name='Relancement',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': '\u7248\u672c\u7ba1\u7406(\u5b89\u5353)', 'verbose_name_plural': '\u7248\u672c\u7ba1\u7406'},
        ),
    ]
