# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0044_auto_20170508_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usb',
            name='sin_data',
            field=models.TextField(verbose_name='\u7b7e\u540d\u6570\u636e'),
        ),
    ]
