# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0045_auto_20170510_0219'),
        ('kernel', '0044_auto_20170427_0401'),
    ]

    operations = [
    ]
